services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    redis:
        image: redis:latest

    backend:
        build: ./backend/
        volumes:
            - ./backend/:/app/backend/
        ports:
            - "8000:8000"
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        depends_on:
            - db
            - redis

    frontend:
        build: ./frontend/
        volumes:
            - ./frontend/:/app/frontend/
        ports:
            - "5173:5173"
        depends_on:
            - backend

volumes:
    postgres_data:
