# Generated by Django 5.2.3 on 2025-07-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_messagemedia_delete_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="avatar_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="description",
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
