# Generated by Django 5.2.3 on 2025-07-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatroom_avatar_img_chatroom_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_dm",
            field=models.BooleanField(default=False),
        ),
    ]
