# Generated by Django 5.2.3 on 2025-07-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatroom_is_dm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="avatar_img",
            field=models.ImageField(blank=True, null=True, upload_to="chat_avatar/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_img",
            field=models.ImageField(blank=True, null=True, upload_to="user_avatar/"),
        ),
    ]
