# Generated by Django 5.2.3 on 2025-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatroom_avatar_img_alter_profile_avatar_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
